name: 🐳 Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ '**' ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner}}/07120:latest
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/07120:latest,mode=max
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository_owner }}/07120:latest
